// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GeneratePlate(arg1:main.PlateRequest):Promise<main.PlateResponse>;

export function GetDefaults():Promise<main.Defaults>;

export function RenderPlate(arg1:main.PlateRequest):Promise<main.PlateResponse>;

export function SaveCurrentPNG(arg1:main.PlateRequest):Promise<string>;
