// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GeneratePlate(arg1) {
  return window['go']['main']['App']['GeneratePlate'](arg1);
}

export function GetDefaults() {
  return window['go']['main']['App']['GetDefaults']();
}

export function RenderPlate(arg1) {
  return window['go']['main']['App']['RenderPlate'](arg1);
}

export function SaveCurrentPNG(arg1) {
  return window['go']['main']['App']['SaveCurrentPNG'](arg1);
}
